docs_mode_category:
  default: ""
  type: list
  list_type: category

style_mode:
  default: "left"
  type: enum
  choices:
    - "top"
    - "left"

replace_breadcrumb_with_filter:
  default: false
  type: bool

svg_icons:
  default: "book|info-circle|landmark|fingerprint|fire|seedling|robot|cake-candles|birthday-cake|trophy|share-nodes"
