docs_mode_category:
  default: ""
  type: list
  list_type: category

style_mode:
  default: "left"
  type: enum
  choices:
    - "top"
    - "left"

svg_icons:
  default: "book|info-circle|landmark|fingerprint|fire|seedling"
